### ISSUE TITLE
输入color值为#333等会不显示

### ISSUE THREAD

**Issue by xueyan1** [iconfont-cli/mini-program-iconfont-cli#1]
设置color="{{['#333', ''#999'']}}"图片不显示，
设置为color="{{['rgb(255,183,85)', 'rgb(103,255,97)']}}"，就可以正常显示。

**Comment by fwh1990** [comment]
似乎是因为小程序里的svg不支持16进制的写法，需要转为rgb的形式。我需要在运行时把`#xxxxxx`写法转换为rgb的格式。

**Comment by fwh1990** [comment]
@xueyan1 发布了新版本，修复不支持 `#xxx`的写法问题
