### ISSUE TITLE
能做一个适配Taro的cli方案吗？

### ISSUE THREAD

**Issue by D1N910** [iconfont-cli/mini-program-iconfont-cli#2]
如题，Taro可以做多端应用，使用您的cli的时候，调用组件时不是很方便，不能多端使用，如果能够有生成Taro的cli，我感觉会很赞。

**Comment by fwh1990** [comment]
在taro中，你是想怎样去调用呢？能给出简单的代码片段吗？

**Comment by fwh1990** [comment]
@D1N910 Hi，我已经有taro的方案了，很快就能开源出来

**Comment by D1N910** [comment]
我直接是用的小程序混写的方案，非常高兴你有了taro的方案，我会布道出去的，希望能够以目前的形式

**Comment by fwh1990** [comment]
Hi，Taro的方案在这里，https://github.com/fwh1990/taro-iconfont-cli ，按照教程走即可。如果有问题，直接在那个项目下给我提issue。除了RN，其他3个平台都测试过了，希望尽快给我反馈。 @D1N910

**Comment by D1N910** [comment]
> Hi，Taro的方案在这里，https://github.com/fwh1990/taro-iconfont-cli ，按照教程走即可。如果有问题，直接在那个项目下给我提issue。除了RN，其他3个平台都测试过了，希望尽快给我反馈。 @D1N910

收到

**Comment by D1N910** [comment]
体验很棒，思路清晰，点赞👍
