### ISSUE TITLE
能支持uniapp吗

### ISSUE THREAD

**Issue by xxasd** [iconfont-cli/mini-program-iconfont-cli#5]

**Comment by fwh1990** [comment]
uniapp还没用过。能说明一下使用场景吗？

**Comment by xxasd** [comment]
> uniapp还没用过。能说明一下使用场景吗？

就是uniapp编译到微信小程序的时候没法用多色的svg，我现在用的也是svg改base64格式方法，但是多色设置这一块我没有好的解决办法，uniapp用的是vue，行内样式如果放base64格式的话它不起效，很头疼

**Comment by fwh1990** [comment]
Ok，我先评估一下。如果有兼容uniapp，应该是会再开一个库。

**Comment by xxasd** [comment]
> Ok，我先评估一下。如果有兼容uniapp，应该是会再开一个库。

好的谢谢

**Comment by nxboo** [comment]
uni 可以理解为mpvue

**Comment by fwh1990** [comment]
目前uni-app的市场占有和taro比如何

**Comment by jsLyLeeHi** [comment]
我在用taro

**Comment by SCC0821** [comment]
https://juejin.cn/post/7056749403104608287          这篇文章告诉了如何在uni-app中使用，完美解决
