### ISSUE TITLE
能支持mpvue吗？

### ISSUE THREAD

**Issue by zhoufanglu** [iconfont-cli/mini-program-iconfont-cli#6]
目前配置了，好像没效果。

**Comment by zhoufanglu** [comment]
![image](https://user-images.githubusercontent.com/24451091/71392473-1bd79900-2643-11ea-9588-b1098c443f1c.png)
目前页面上是这个效果
```html
<iconfont name="icon-tab_icon_shop_s" />
```
这是代码

**Comment by zhoufanglu** [comment]
![image](https://user-images.githubusercontent.com/24451091/71395595-8ee80c00-2651-11ea-9e19-d772f4dc0f5c.png)


经过配置 显示出来了

**Comment by fwh1990** [comment]
这个帖子和mpvue有啥关系？
